/**
 * A single expense entry — like one row in a spreadsheet.
 *
 * Every time the user logs a purchase or payment, we create one Expense object.
 * It is stored in the SQLite database and displayed in the app's tables and charts.
 */
export interface Expense {
  /**
   * Unique database row ID. It is **optional** because when the user creates
   * a new expense the database hasn't assigned an ID yet — SQLite auto-generates
   * it the moment the row is saved. If undefined, the expense is brand-new.
   */
  id?: number

  /**
   * How much money was spent, stored as a plain number (e.g. 42.99).
   * We use `number` rather than a string so we can do math on it:
   * adding up totals, averaging, etc.
   */
  amount: number

  /**
   * The first (broader) half of a two-level category system.
   * Example: "Food" is a primary category, and "Groceries" is a secondary
   * category nested underneath it. This gives the user more precise ways to
   * group and filter their spending.
   */
  primary_category: string

  /**
   * The second (narrower) half of the two-level category system.
   * Example: under "Food" (primary), you might have "Groceries",
   * "Restaurants", or "Coffee" as secondary categories.
   */
  secondary_category: string

  /**
   * The date the expense happened, stored as a string in "YYYY-MM-DD" format
   * (e.g. "2026-07-06"). This format sorts correctly as plain text and is
   * easy to display in date-picker components.
   */
  date: string

  /**
   * Free-form text the user can add to describe the expense.
   * It is optional in the UI — many users leave it blank.
   * When absent it defaults to an empty string ("").
   */
  note: string

  /** Timestamp of when the row was first inserted into the database. Auto-set by SQLite. */
  created_at?: string

  /** Timestamp of the last time the row was modified. Auto-updated by SQLite. */
  updated_at?: string
}

/**
 * A single option inside a cascading (cascader) dropdown.
 *
 * Ant Design's Cascader component expects data in this shape.
 * Top-level categories (like "Food") have a `children` array containing
 * secondary categories (like "Groceries", "Restaurants"). If `children`
 * is undefined or empty, this option is a leaf with no sub-options.
 */
export interface CategoryOption {
  /** Internal key used to identify the category in code (e.g. "food-groceries"). */
  value: string
  /** Human-readable name shown to the user (e.g. "Groceries"). */
  label: string
  /** Nested sub-categories, if any. Undefined means "this is a leaf." */
  children?: CategoryOption[]
}

/**
 * A custom category that the user created themselves.
 *
 * The app ships with a set of **built-in categories** (like "Food",
 * "Transportation", "Entertainment") that cover common expenses. But every
 * person's spending is unique — maybe you need a "Pet Supplies" category
 * or a "Podcast Subscriptions" category.
 *
 * This interface represents those user-created categories. They live in a
 * separate database table from the built-in ones, but the app seamlessly
 * merges both sources (see MergedCategoryNode) so the user sees one unified
 * picker instead of two separate lists.
 */
export interface UserCategory {
  /** Database row ID (auto-generated by SQLite, undefined for brand-new entries). */
  id?: number
  /** The broader category name the user chose (e.g. "Personal"). */
  primary_category: string
  /** The narrower sub-category name (e.g. "Haircuts"). */
  secondary_category: string
  /** When the category was first created. Auto-set by SQLite. */
  created_at?: string
}

/**
 * A category node that combines built-in and user-created categories into
 * one unified tree.
 *
 * ## Why this exists
 *
 * The app has two separate sources of categories:
 *   1. **Built-in** — factory defaults shipped with the app (e.g. "Food").
 *   2. **User-created** — custom categories the user added themselves.
 *
 * Rather than forcing the user to switch between two pickers, we merge them
 * into a single, seamless list via this type. The `isBuiltin` flag lets the
 * UI decide whether to show an edit/delete button (user categories can be
 * modified; built-in ones cannot).
 */
export interface MergedCategoryNode {
  /** Internal key (same format as CategoryOption.value). */
  value: string
  /** Display name shown to the user. */
  label: string
  /**
   * `true` means this category came from the app's factory defaults and
   * cannot be deleted or renamed. `false` means the user created it, so
   * the UI may offer edit/delete controls.
   */
  isBuiltin: boolean
  /**
   * Sub-categories nested under this primary category. Each child also
   * carries its own `isBuiltin` flag so the UI can handle mixed trees
   * (e.g. a built-in primary category with a user-created secondary one).
   */
  children: { value: string; label: string; isBuiltin: boolean }[]
}
